# Generated by Django 3.1.4 on 2021-01-21 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='sqft',
            new_name='CarpetArea',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='garage',
            new_name='Parking',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='lot_size',
            new_name='SuperArea',
        ),
    ]
