# Generated by Django 3.1.4 on 2021-01-20 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calcs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calc',
            name='listin_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
