# Generated by Django 3.1.4 on 2021-01-20 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calcs', '0002_calc_listin_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calc',
            name='listin_id',
        ),
    ]
